---
- name: Extract the zipped artifact
  become: yes
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: .
    
- name: Start the app
  become: yes
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start